name: ✏️ 블로그 포스팅 공유
description: 작성한 포스팅을 공유해주세요
title: "✏️ 포스팅 제목"
labels: "초안"
assignees:
  - BangDori
  - asuan99
  - youngsu5582
  - psychology50
body:
  - type: input
    id: summary
    attributes:
      label: 내용 (한줄 요약)
      description: 블로그 포스트의 내용을 한 줄로 요약해주세요.
      placeholder: 내용을 입력해 주세요.
    validations:
      required: true
  - type: input
    id: target_audience
    attributes:
      label: 예상 독자
      description: 이 블로그 포스트의 예상 독자는 누구인가요?
      placeholder: 서버 개발자, 앱 개발자, 디자이너 등
    validations:
      required: true
  - type: input
    id: blog_link
    attributes:
      label: 블로그 링크
      description: 관련된 블로그 링크가 있다면 공유해주세요.
      placeholder: http://example.com
    validations:
      required: true
